### PR TITLE
layout for dark mode

### PR DESCRIPTION
**Pull request by ElvinPero**

### CODE REVIEW

**Comment by DevoAbhi** [comment]
This layout does not serve the purpose of the app. The input fields are not styled so it does not make any useful effect.

**Comment by ElvinPero** [comment]
> This layout does not serve the purpose of the app. The input fields are not styled so it does not make any useful effect.

the layout provides basic design for site . I will add night mode on it once its merged as it will show the place for nav and other options that can be removed later. 
image

**Comment by DevoAbhi** [comment]
The layout itself is very good.

1) This app is not a chat app, it is an app to send scheduled msgs. So a form would suffice. 
2) Therefore I would suggest to build a simple form using bootstrap or other templates and that would be a basic design.

I would love to hear your thoughts.

**Comment by ElvinPero** [comment]
@DevoAbhi ok so since someone else is working on the layout i can just add the dark mode button on the current master ok?

**Pull request closed without merging**
