### PR TITLE
dark button added

### PR DESCRIPTION
**Pull request by iamdestinychild**
I added the dark mode button and added the toggle for effect, with moon and sun icons for visualization

### CODE REVIEW

**Comment by DevoAbhi** [comment]
Great work!
Just that the animations are not being shown in dark mode. Is it possible you can fix that?

**Comment by iamdestinychild** [comment]
yes sure

**Comment by iamdestinychild** [comment]
done

**Comment by DevoAbhi** [comment]
Sorry was out, will check now.

**Comment by DevoAbhi** [comment]
Great work man!
LGTM

**Pull request merged**
